### ISSUE TITLE
tasks

### ISSUE THREAD

**Issue by hiagoptk** [hiagoptk/hiagoptk.github.io#1]
Objective: Build a CodePen.io app that is functionally similar to this: https://codepen.io/freeCodeCamp/full/zNBOYG.

- [x] User Story #1: My portfolio should have a welcome section with an id of welcome-section.

- [ ] User Story #2: The welcome section should have an h1 element that contains text.

- [ ] User Story #3: My portfolio should have a projects section with an id of projects.

- [ ] User Story #4: The projects section should contain at least one element with a class of project-tile to hold a project.

- [ ] User Story #5: The projects section should contain at least one link to a project.

- [x] User Story #6: My portfolio should have a navbar with an id of navbar.

- [ ] User Story #7: The navbar should contain at least one link that I can click on to navigate to different sections of the page.

- [ ] User Story #8: My portfolio should have a link with an id of profile-link, which opens my GitHub or FCC profile in a new tab.

- [ ] User Story #9: My portfolio should have at least one media query.

- [ ] User Story #10: The height of the welcome section should be equal to the height of the viewport.

- [ ] User Story #11: The navbar should always be at the top of the viewport.
